version: "3.8"
services:
  eca:
    build: .
    environment:
      MONGO_URI: mongodb://mongo:27017/ECA
  mongo:
    image: mongo:7
    restart: unless-stopped
    command: ["mongod", "--bind_ip_all"]
    volumes:
      - ./eca_data/mongo_db:/data/db
    ports:
      - 27017:27017

